TT:
  # CIB & SZ
  cib_index: -1.3
  A_cib_217:
    prior:
      dist: uniform
      min: 0
      max: 200
    ref:
      dist: norm
      loc: 67
      scale: 10
    proposal: 1.2
    latex: A^\mathrm{CIB}_{217}
  xi_sz_cib:
    prior:
      dist: uniform
      min: 0
      max: 1
    ref:
      dist: halfnorm
      loc: 0
      scale: 0.1
    proposal: 0.1
    latex: \xi^{\mathrm{tSZ}\times\mathrm{CIB}}
  A_sz:
    prior:
      dist: uniform
      min: 0
      max: 10
    ref:
      dist: norm
      loc: 7
      scale: 2
    proposal: 0.6
    latex: A^\mathrm{tSZ}_{143}
  ksz_norm:
    prior:
      dist: uniform
      min: 0
      max: 10
    ref:
      dist: halfnorm
      loc: 0
      scale: 3
    proposal: 1
    latex: A^\mathrm{kSZ}
  # Dust priors
  gal545_A_100:
    prior:
      dist: norm
      loc: 8.6
      scale: 2
    ref:
      dist: norm
      loc: 7
      scale: 2
    proposal: 1
    latex: A^\mathrm{dustTT}_{100}
  gal545_A_143:
    prior:
      dist: norm
      loc: 10.6
      scale: 2
    ref:
      dist: norm
      loc: 9
      scale: 2
    proposal: 1
    latex: A^\mathrm{dustTT}_{143}
  gal545_A_143_217:
    prior:
      dist: norm
      loc: 23.5
      scale: 8.5
    ref:
      dist: norm
      loc: 21
      scale: 4
    proposal: 1.5
    latex: A^\mathrm{dustTT}_{\mathrm{143}\times\mathrm{217}}
  gal545_A_217:
    prior:
      dist: norm
      loc: 91.9
      scale: 20
    ref:
      dist: norm
      loc: 80
      scale: 15
    proposal: 2
    latex: A^\mathrm{dustTT}_{217}
  # Subpixel effect
  A_sbpx_100_100_TT: 1
  A_sbpx_143_143_TT: 1
  A_sbpx_143_217_TT: 1
  A_sbpx_217_217_TT: 1
  # Point source contributions
  ps_A_100_100:
    prior:
      dist: uniform
      min: 0
      max: 400
    ref:
      dist: norm
      loc: 257
      scale: 24
    proposal: 17
    latex: A^\mathrm{PS}_{100}
  ps_A_143_143:
    prior:
      dist: uniform
      min: 0
      max: 400
    ref:
      dist: norm
      loc: 47
      scale: 10
    proposal: 3
    latex: A^\mathrm{PS}_{143}
  ps_A_143_217:
    prior:
      dist: uniform
      min: 0
      max: 400
    ref:
      dist: norm
      loc: 40
      scale: 12
    proposal: 2
    latex: A^\mathrm{PS}_{\mathrm{143}\times\mathrm{217}}
  ps_A_217_217:
    prior:
      dist: uniform
      min: 0
      max: 400
    ref:
      dist: norm
      loc: 104
      scale: 13
    proposal: 2.5
    latex: A^\mathrm{PS}_{217}

TE:
  galf_TE_index: -2.4
  galf_TE_A_100:
    prior:
      dist: norm
      loc: 0.130
      scale: 0.042
    ref:
      dist: norm
      loc: 0.130
      scale: 0.1
    proposal: 0.1
    latex: A^\mathrm{dustTE}_{100}
  galf_TE_A_100_143:
    prior:
      dist: norm
      loc: 0.130
      scale: 0.036
    ref:
      dist: norm
      loc: 0.130
      scale: 0.1
    proposal: 0.1
    latex: A^\mathrm{dustTE}_{\mathrm{100}\times\mathrm{143}}
  galf_TE_A_100_217:
    prior:
      dist: norm
      loc: 0.46
      scale: 0.09
    ref:
      dist: norm
      loc: 0.46
      scale: 0.10
    proposal: 0.10
    latex: A^\mathrm{dustTE}_{\mathrm{100}\times\mathrm{217}}
  galf_TE_A_143:
    prior:
      dist: norm
      loc: 0.207
      scale: 0.072
    ref:
      dist: norm
      loc: 0.207
      scale: 0.100
    proposal: 0.100
    latex: A^\mathrm{dustTE}_{143}
  galf_TE_A_143_217:
    prior:
      dist: norm
      loc: 0.69
      scale: 0.09
    ref:
      dist: norm
      loc: 0.69
      scale: 0.1
    proposal: 0.1
    latex: A^\mathrm{dustTE}_{\mathrm{143}\times\mathrm{217}}
  galf_TE_A_217:
    prior:
      dist: norm
      loc: 1.938
      scale: 0.54
    ref:
      dist: norm
      loc: 1.938
      scale: 0.2
    proposal: 0.2
    latex: A^\mathrm{dustTE}_{217}

EE:
  # EE now recommended to be left to the central values of the stated priors
  galf_EE_index: -2.4
  galf_EE_A_100:
    value: 0.055  # (± 0.014)
    latex: A^\mathrm{dustEE}_{100}
  galf_EE_A_100_143:
    value: 0.040  # (± 0.010)
    latex: A^\mathrm{dustEE}_{\mathrm{100}\times\mathrm{143}}
  galf_EE_A_100_217:
    value: 0.094  # (± 0.023)
    latex: A^\mathrm{dustEE}_{\mathrm{100}\times\mathrm{217}}
  galf_EE_A_143:
    value: 0.086  # (± 0.022)
    latex: A^\mathrm{dustEE}_{143}
  galf_EE_A_143_217:
    value: 0.21  # (± 0.051)
    latex: A^\mathrm{dustEE}_{\mathrm{143}\times\mathrm{217}}
  galf_EE_A_217:
    value: 0.70  # (± 0.18)
    latex: A^\mathrm{dustEE}_{217}
  # EE End2End correlated noise
  A_cnoise_e2e_100_100_EE: 1
  A_cnoise_e2e_143_143_EE: 1
  A_cnoise_e2e_217_217_EE: 1
  A_sbpx_100_100_EE: 1
  A_sbpx_100_143_EE: 1
  A_sbpx_100_217_EE: 1
  A_sbpx_143_143_EE: 1
  A_sbpx_143_217_EE: 1
  A_sbpx_217_217_EE: 1

calib:
  A_planck:
    prior:
      dist: norm
      loc: 1
      scale: 0.0025
    ref:
      dist: norm
      loc: 1
      scale: 0.002
    proposal: 0.0005
    latex: y_\mathrm{cal}

calib_temp:
  calib_100T:
    prior:
      dist: norm
      loc: 1.0002
      scale: 0.0007
    ref:
      dist: norm
      loc: 1.0002
      scale: 0.001
    proposal: 0.0005
    latex: c_{100}
  calib_217T:
    prior:
      dist: norm
      loc: 0.99805
      scale: 0.00065
    ref:
      dist: norm
      loc: 0.99805
      scale: 0.001
    proposal: 0.0005
    latex: c_{217}

calib_pol:
  A_pol: 1
  calib_100P: 1.021  # (± 0.01)
  calib_143P: 0.966  # (± 0.01)
  calib_217P: 1.040  # (± 0.01)

prior_SZ:
  SZ:
    derived: '{ksz_norm} + 1.6 * {A_sz}'
    prior:
      dist: 'norm'
      loc: 9.5
      scale: 3.
    drop: True
